### ISSUE TITLE
申请jan/11号图片授权

### ISSUE THREAD

**Issue by CasterWx** [phodal/daily#3]
您好，我是AntzOs的开发者，最近希望在操作系统开始启动时有一个启动动画，从知乎关注您的日常练习很久了，觉得里面大部分画都很有特点，所以想将jan/11号图片做为启动界面。(虽然说您的作品是开源的，但是我旁边的同学看到我要拿来用，强行要求我向您申请授权)

这个是我的那个操作系统 [https://github.com/CasterWx/AntzOS](https://github.com/CasterWx/AntzOS)

**Comment by phodal** [comment]
Hello, 

欢迎使用哈 @CasterWx 。

不过，值得注意的是，这张图都是模仿品哈，是不能用于商业用途的。

原图是：https://www.amazon.cn/gp/product/B073LZD7PS/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1

**Comment by CasterWx** [comment]
非常感谢 ! @phodal

**Comment by CasterWx** [comment]
初步完成啦，现在还是按照像素点的方式显示的，显示不是很清楚  @phodal 

![img](https://github.com/CasterWx/AntzOS/raw/master/screen/runShow.gif)

**Comment by Medicalcottonball** [comment]
我觉得有点给力！可以在你的引导界面放上我的大头贴吗？我出十块！

**Comment by phodal** [comment]
@Medicalcottonball 图呢

**Comment by Medicalcottonball** [comment]
> 
> 
> @Medicalcottonball 图呢
我自闭了，我怎么用过github，我以为这个话会给CasterWx发私信的，不好意思啊

**Comment by phodal** [comment]
@Medicalcottonball 没别的意思，我就是想看大头贴，哈哈
